# Generated by Django 4.2.3 on 2023-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
